### ISSUE TITLE
File not found error in some of the API methods

### ISSUE THREAD

**Issue by erikhuck** [filippocastelli/KEGGutils#11]
After fresh install of KEGGutils in a virtual environment:
```
>>> import KEGGutils as kg
>>> kg.keggapi_list('hsa')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/erikhuckvale/tmp/.env/lib/python3.10/site-packages/KEGGutils/KEGGapi.py", line 533, in keggapi_list
    org_codes = get_organism_codes()
  File "/Users/erikhuckvale/tmp/.env/lib/python3.10/site-packages/KEGGutils/KEGGapi.py", line 1003, in get_organism_codes
    organism_fulltext = org_codespath.read_text()
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/virtualenv/.env/lib/python3.10/site-packages/KEGGutils/res/org_codes.txt'
```

**Comment by leitouran** [comment]
Same here!

**Comment by erikhuck** [comment]
@leitouran Have you tried using [kegg-pull](https://pypi.org/project/kegg-pull/) instead? The package has a command line and you can accomplish the task above via `kegg_pull entry-ids database hsa`.

**Comment by leitouran** [comment]
No, but I went to the method a realized I could create my own organisms and put it there. Seems to have solved the issue. 

![image](https://github.com/filippocastelli/KEGGutils/assets/390822/a9fa2ba7-324a-4110-9997-3d5edd7a9407)

Recovered all codes from here: https://www.genome.jp/kegg/genome/

**Comment by erikhuck** [comment]
@leitouran You may still want to give kegg-pull a try. It has additional features, including being able to pull all entries in an entire kegg database using multiprocessing to speed up the process.

**Comment by leitouran** [comment]
It looks pretty neat. I will definitely give it try!

Thank you, Erik!

**Comment by erikhuck** [comment]
@leitouran You are so welcome Lionel!
