### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [filippocastelli/KEGGutils#6]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.3.3. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary keggutils -w /tmp/ext keggutils==0.3.3
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting keggutils==0.3.3
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/26a/1f6f737c42cff/KEGGutils-0.3.3.tar.gz (22 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-ydlbw80p/keggutils/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-ydlbw80p/keggutils/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-ydlbw80p/keggutils/pip-egg-info
         cwd: /tmp/pip-wheel-ydlbw80p/keggutils/
    Complete output (13 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-ydlbw80p/keggutils/setup.py", line 31, in <module>
        install_requires= get_requirements(),
      File "/tmp/pip-wheel-ydlbw80p/keggutils/setup.py", line 15, in get_requirements
        reqs = reqpath.read_text().splitlines()
      File "/usr/lib/python3.8/pathlib.py", line 1227, in read_text
        with self.open(mode='r', encoding=encoding, errors=errors) as f:
      File "/usr/lib/python3.8/pathlib.py", line 1213, in open
        return io.open(self, mode, buffering, encoding, errors, newline,
      File "/usr/lib/python3.8/pathlib.py", line 1069, in _opener
        return self._accessor.open(self, flags, mode)
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by filippocastelli** [comment]
HiI! sorry for not solving the issue earlier, I'm not actively maintaining the repo very often and I totally missed the notification.
In 151a3e58010761e9e56592da8177c2a0b4a0cd2a I've added a MANIFEST.in that solves the build issues in v0.3.4
Thank you for your input!

Have a nice day!
Phil
